server:
  port: 9080
  servlet:
    context-path: /example-api/v1.0

spring:
  profiles:
    default: development
    active: development
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  
      ddl-auto: update

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

---

spring:
  profiles: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/example_api
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

---

spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/example_api_production
    username: example_api_production
    password: example_api_production